<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RetroVideo</AssemblyName>
    <RootNamespace>RetroVideo.Win</RootNamespace>
    <Version>0.2.0</Version>
  </PropertyGroup>
</Project>
